[program:kx_sidekick]
directory=/opt/KaringX/karing_sidekick
command=/usr/bin/env uv run python -m kx_sidekick worker
autostart=true
autorestart=true
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/opt/KaringX/karing_sidekick/logs/kx_sidekick.stdout.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile=/opt/KaringX/karing_sidekick/logs/kx_sidekick.stderr.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
environment=PYTHONUNBUFFERED="1"

[program:kx_sidekick_media_down]
directory=/opt/KaringX/karing_sidekick
command=/usr/bin/env uv run python -m kx_sidekick media-down
autostart=true
autorestart=true
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/opt/KaringX/karing_sidekick/logs/kx_sidekick_media_down.stdout.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile=/opt/KaringX/karing_sidekick/logs/kx_sidekick_media_down.stderr.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
environment=PYTHONUNBUFFERED="1"
